### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xhyrom** [xHyroM/bun-utilities#4]
- [x] Fix bun tests (https://github.com/xHyroM/bun-utilities/runs/7327913838?check_suite_focus=true)
- [x] Add `copySync` like in `fs-extra`
   ^ Probably `copyDirectory` because `copyFile` exists
- [x] Add `rmdir`
- [x] https://github.com/xHyroM/bun-utilities/issues/5
- [x] Delete non required bindings files (https://github.com/xHyroM/bun-utilities/issues/6)
- [x] Fix CI for android builds (because https://github.com/actions/virtual-environments/issues/5879)
- [ ] os

**Comment by targetlucked69** [comment]
Hey thanks for this awesome lib!

I have a question (or maybe this is a Bun specific issue).. how can we do this in Bun right now?

```ts
const p = Deno.run({
  cmd: command,
  stderr: "piped",
  stdout: "piped"
});
for await (const line of readLines(p.stdout)) {
}
```

with your lib we can do...

```ts
import { exec } from 'bun-utilities'

const p = exec(command);

// How to readline?
```

How do we `readline` now? Or do we have other way of reading stdout? Thanks!

**Comment by xhyrom** [comment]
> Hey thanks for this awesome lib!
> 
> I have a question (or maybe this is a Bun specific issue).. how can we do this in Bun right now?
> 
> ```ts
> const p = Deno.run({
>   cmd: command,
>   stderr: "piped",
>   stdout: "piped"
> });
> for await (const line of readLines(p.stdout)) {
> }
> ```
> 
> with your lib we can do...
> 
> ```ts
> import { exec } from 'bun-utilities'
> 
> const p = exec(command);
> 
> // How to readline?
> ```
> 
> How do we `readline` now? Or do we have other way of reading stdout? Thanks!

exec returns `stdout` as string
